# The name of the GPIO input line (to the lock detection switch).
in_line: "GPIO1"

# The name of the GPIO output line (to the unlocking circuit).
out_line: "GPIO2"

# The name of the GPIO output line (to the beeper).
piezo_line: "GPIO3"

# The GPIO chip device. Probably leave this alone.
chip: "/dev/gpiochip0"

# The name of the GPIO consumer (just for display purposes).
consumer: "lock-controller"

# Port number for listening for incoming socket connections.
port: 12345

# Password to be sent to unlock the door.
password: "abcdefg12345"

# Beep times when the door is unlocked.
unlock_beep_times: [ 0, 0.5, 1, 10, 10.5, 11, 20, 20.5, 21, 30, 30.5, 31 ]
